version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test-core:
    working_directory: ~/contracts-wizard/packages/core
    machine:
      image: ubuntu-2004:2023.04.2
      resource_class: medium
    steps:
      - node/install:
          node-version: '18.15'
      - checkout:
          path: ~/contracts-wizards
      - node/install-packages:
          app-dir: ~/contracts-wizards
      - run:
          name: Run tests
          command: npm run test

workflows:
  core:
    jobs:
      - test-core
